version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - rust

  - package-ecosystem: nuget
    directory: "/Myriad"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dotnet

  - package-ecosystem: nuget
    directory: "/PluralKit.API"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dotnet

  - package-ecosystem: nuget
    directory: "/PluralKit.Bot"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dotnet

  - package-ecosystem: nuget
    directory: "/PluralKit.Core"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dotnet

  - package-ecosystem: nuget
    directory: "/PluralKit.Tests"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dotnet

  - package-ecosystem: npm
    directory: "/dashboard"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - npm

  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - npm

  - package-ecosystem: gomod
    directory: "/dashboard"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - go

  - package-ecosystem: docker
    directory: "/ci"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: "/dashboard"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: "/docs"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
