services:

  migrate:
    image: ghcr.io/${GHCR_OWNER}/copycat:latest
    environment:
      - "COPYCAT_MIGRATE_ONLY=true"
      - "PluralKit__Database=Host=db;Username=postgres;Password=postgres;Database=postgres"
    command: ["bin/PluralKit.Bot.dll"]
    depends_on:
      db:
        condition: service_healthy

  register-commands:
    image: ghcr.io/${GHCR_OWNER}/copycat:latest
    command: ["bin/PluralKit.Bot.dll"]
    environment:
      - "COPYCAT_REGISTER_COMMANDS_ONLY=true"
      - "PluralKit__Bot__Token=${BOT_TOKEN}"
      - "PluralKit__Bot__ClientId=${CLIENT_ID}"
    restart: "no"

  bot:
    image: ghcr.io/${GHCR_OWNER}/copycat:latest
    command: ["bin/PluralKit.Bot.dll"]
    volumes:
      - "/data/piper:/app/piper"
      - "/data/cabal:/app/cabal"
    environment:
      - "COPYCAT_TTS_DOWNLOAD_VOICES=1"
      - "PluralKit__Database=Host=db;Username=postgres;Password=postgres;Database=postgres"
      - "PluralKit__RedisAddr=redis"
      - "PluralKit__Bot__Token=${BOT_TOKEN}"
      - "PluralKit__Bot__ClientId=${CLIENT_ID}"
      - "PluralKit__Bot__AdminRole=${ADMIN_ROLE}"
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started

  db:
    image: postgres:17-alpine
    volumes:
      - "/data/db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  db:
  piper:
  cabal:
