using System.Diagnostics;

using Myriad.Rest.Types;

using PluralKit.Core;

using Serilog;

namespace PluralKit.Bot;

public sealed record GeneratedVoiceClip(MultipartFile File, string TempPath): IDisposable
{
    public void Dispose()
    {
        try
        {
            File.Data.Dispose();
        }
        catch
        {
            // ignore stream disposal errors
        }

        try
        {
            if (global::System.IO.File.Exists(TempPath))
                global::System.IO.File.Delete(TempPath);
        }
        catch
        {
            // ignore temp-file cleanup errors
        }
    }
}

public class TtsVoiceService
{
    private readonly ILogger _logger;
    private HashSet<string> _availableVoiceIds = new(StringComparer.OrdinalIgnoreCase);

    public TtsVoiceService(ILogger logger)
    {
        _logger = logger.ForContext<TtsVoiceService>();
    }

    /// <summary>
    /// Probes which voice IDs from <paramref name="voiceIds"/> are actually usable
    /// given the files present on disk, caches the result, and logs a summary.
    /// Call this once at bot startup.
    /// </summary>
    public void ProbeAvailability(IEnumerable<string> voiceIds)
    {
        var scriptPath = TryResolveScriptPath();
        var scriptDir  = scriptPath != null ? Path.GetDirectoryName(scriptPath) : null;

        var available  = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var unavailable = new List<string>();

        foreach (var id in voiceIds)
        {
            if (CheckVoiceAvailable(id, scriptDir))
                available.Add(id);
            else
                unavailable.Add(id);
        }

        _availableVoiceIds = available;

        _logger.Information("TTS availability: {Available} voice(s) ready, {Unavailable} unavailable",
            available.Count, unavailable.Count);

        if (unavailable.Count > 0)
            _logger.Warning("TTS voices unavailable (missing files): {Voices}",
                string.Join(", ", unavailable));
    }

    public bool IsVoiceAvailable(string voiceId) =>
        _availableVoiceIds.Contains(voiceId);

    private static bool CheckVoiceAvailable(string voiceId, string? scriptDir)
    {
        var voiceLower = voiceId.Trim().ToLowerInvariant();

        if (voiceLower is "morshu" or "cabal")
        {
            // Python bridge: the generator script must exist and the relevant
            // vendor directory must be present.
            if (scriptDir == null)
                return false;

            var vendorName = voiceLower == "morshu" ? "MorshuTalk" : "TiberianSunCABAL-Talk";
            return Directory.Exists(Path.Combine(scriptDir, "vendors", vendorName));
        }

        // Piper voice: the ONNX model file must be present.
        return FindPiperModel(voiceId) != null;
    }

    public async Task<GeneratedVoiceClip> GenerateClip(string voiceId, string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            throw new PKError("Text cannot be empty.");
        if (string.IsNullOrWhiteSpace(voiceId))
            throw new PKError("Voice cannot be empty.");

        var voice = voiceId.Trim();
        var voiceLower = voice.ToLowerInvariant();

        // morshu and cabal are generated by the Python bridge using their vendor libraries.
        // All other voices are handled directly by the Piper TTS binary (no Python needed).
        if (voiceLower is "morshu" or "cabal")
            return await GeneratePythonClip(voice, text);

        return await GeneratePiperClip(voice, text);
    }

    // ── Piper TTS (neural voices, called directly from C#) ───────────────────

    private async Task<GeneratedVoiceClip> GeneratePiperClip(string voiceId, string text)
    {
        var modelPath = FindPiperModel(voiceId)
            ?? throw new PKError($"Voice model '{voiceId}' not found.");

        var outputPath = Path.Combine(Path.GetTempPath(), $"copycat-tts-{Guid.NewGuid():N}.wav");

        // piper-tts is installed as a Python package; invoke it via `python3 -m piper`.
        var pythonOverride = Environment.GetEnvironmentVariable("COPYCAT_TTS_PYTHON");
        var python = string.IsNullOrWhiteSpace(pythonOverride) ? "python3" : pythonOverride;

        var psi = new ProcessStartInfo
        {
            FileName = python,
            RedirectStandardInput = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        psi.ArgumentList.Add("-m");
        psi.ArgumentList.Add("piper");
        psi.ArgumentList.Add("--model");
        psi.ArgumentList.Add(modelPath);
        psi.ArgumentList.Add("--output_file");
        psi.ArgumentList.Add(outputPath);

        using var process = Process.Start(psi)
            ?? throw new PKError("Could not start piper-tts process.");

        // Piper can clip the final phoneme on short/plain text; add a terminal
        // pause marker so synthesis has room to finish naturally.
        await process.StandardInput.WriteAsync(PreparePiperInput(text));
        process.StandardInput.Close();

        var stderrTask = process.StandardError.ReadToEndAsync();
        await process.WaitForExitAsync();
        var stderr = await stderrTask;

        if (process.ExitCode != 0)
        {
            _logger.Warning("piper-tts exited with code {ExitCode}: {Stderr}", process.ExitCode, stderr);
            throw new PKError($"Voice generation failed (piper exit {process.ExitCode}).");
        }

        if (!global::System.IO.File.Exists(outputPath))
            throw new PKError("piper-tts did not create an output file.");

        // Add a tiny silence tail so Discord playback doesn't feel abruptly cut.
        TryAppendWaveSilence(outputPath, 120);

        var stream = new FileStream(outputPath, FileMode.Open, FileAccess.Read, FileShare.Read);
        var safeVoice = string.Concat(voiceId.Select(ch => char.IsLetterOrDigit(ch) || ch == '-' || ch == '_' ? ch : '_')).ToLowerInvariant();
        var multipart = new MultipartFile($"tts-{safeVoice}.wav", stream, "Generated voice clip", null, null, false);
        return new GeneratedVoiceClip(multipart, outputPath);
    }

    private static string PreparePiperInput(string text)
    {
        var normalized = text.TrimEnd();
        if (normalized.Length == 0)
            return " .";

        if (normalized.EndsWith('.'))
            return normalized;

        return normalized + " .";
    }

    private static void TryAppendWaveSilence(string path, int silenceMs)
    {
        if (silenceMs <= 0)
            return;

        try
        {
            using var fs = new FileStream(path, FileMode.Open, FileAccess.ReadWrite, FileShare.Read);
            using var br = new BinaryReader(fs);

            if (fs.Length < 44)
                return;

            fs.Seek(22, SeekOrigin.Begin);
            var channels = br.ReadInt16();
            var sampleRate = br.ReadInt32();
            fs.Seek(34, SeekOrigin.Begin);
            var bitsPerSample = br.ReadInt16();

            if (channels <= 0 || sampleRate <= 0 || bitsPerSample <= 0)
                return;

            var bytesPerSample = bitsPerSample / 8;
            if (bytesPerSample <= 0)
                return;

            var silenceBytes = sampleRate * channels * bytesPerSample * silenceMs / 1000;
            if (silenceBytes <= 0)
                return;

            fs.Seek(0, SeekOrigin.End);
            fs.Write(new byte[silenceBytes]);

            var newFileSize = checked((uint)fs.Length - 8);
            var newDataSize = checked((uint)fs.Length - 44);

            fs.Seek(4, SeekOrigin.Begin);
            fs.Write(BitConverter.GetBytes(newFileSize));
            fs.Seek(40, SeekOrigin.Begin);
            fs.Write(BitConverter.GetBytes(newDataSize));
        }
        catch
        {
            // Best effort only: if header parsing fails, keep the synthesized file.
        }
    }

    private static string? FindPiperBinary() => null; // kept for compatibility; piper is now invoked via python -m piper

    private static string? FindPiperModel(string voiceId)
    {
        var candidates = new[]
        {
            $"/app/piper-voices/{voiceId}.onnx",
            Path.Combine(AppContext.BaseDirectory, "piper-voices", $"{voiceId}.onnx"),
        };
        return candidates.FirstOrDefault(global::System.IO.File.Exists);
    }

    // ── Python bridge (morshu / cabal) ───────────────────────────────────────

    private async Task<GeneratedVoiceClip> GeneratePythonClip(string voiceId, string text)
    {
        var outputPath = Path.Combine(Path.GetTempPath(), $"copycat-tts-{Guid.NewGuid():N}.wav");
        var scriptPath = ResolveScriptPath();

        var pythonOverride = Environment.GetEnvironmentVariable("COPYCAT_TTS_PYTHON");
        var pythonCandidates = string.IsNullOrWhiteSpace(pythonOverride)
            ? new[] { "python", "python3" }
            : new[] { pythonOverride };

        var lastError = string.Empty;
        foreach (var python in pythonCandidates)
        {
            var result = await RunPythonGenerator(python, scriptPath, voiceId, text, outputPath);
            if (result.Success)
            {
                if (!global::System.IO.File.Exists(outputPath))
                    throw new PKError("TTS generation completed but no output file was created.");

                var stream = new FileStream(outputPath, FileMode.Open, FileAccess.Read, FileShare.Read);
                var safeVoice = string.Concat(voiceId.Select(ch => char.IsLetterOrDigit(ch) ? ch : '_')).ToLowerInvariant();
                var multipart = new MultipartFile($"tts-{safeVoice}.wav", stream, "Generated voice clip", null, null, false);
                return new GeneratedVoiceClip(multipart, outputPath);
            }
            lastError = result.Error;
        }

        throw new PKError($"TTS generation failed. {lastError}");
    }

    private async Task<(bool Success, string Error)> RunPythonGenerator(string pythonCommand, string scriptPath,
                                                                         string voice, string text, string outputPath)
    {
        try
        {
            var psi = new ProcessStartInfo
            {
                FileName = pythonCommand,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
                WorkingDirectory = Path.GetDirectoryName(scriptPath) ?? AppContext.BaseDirectory
            };
            psi.ArgumentList.Add(scriptPath);
            psi.ArgumentList.Add("--voice");
            psi.ArgumentList.Add(voice);
            psi.ArgumentList.Add("--text");
            psi.ArgumentList.Add(text);
            psi.ArgumentList.Add("--out");
            psi.ArgumentList.Add(outputPath);

            using var process = Process.Start(psi);
            if (process == null)
                return (false, $"Could not start {pythonCommand}.");

            var stdoutTask = process.StandardOutput.ReadToEndAsync();
            var stderrTask = process.StandardError.ReadToEndAsync();
            await process.WaitForExitAsync();
            var stdout = await stdoutTask;
            var stderr = await stderrTask;

            if (process.ExitCode == 0)
                return (true, string.Empty);

            _logger.Warning("TTS generator exited with code {ExitCode}. stdout={Stdout} stderr={Stderr}",
                process.ExitCode, stdout, stderr);
            var trimmed = string.IsNullOrWhiteSpace(stderr) ? stdout : stderr;
            if (trimmed.Length > 400) trimmed = trimmed[..400] + "...";
            return (false, $"Generator ({pythonCommand}) exited with code {process.ExitCode}. {trimmed}.");
        }
        catch (Exception e)
        {
            return (false, $"Failed to launch generator ({pythonCommand}): {e.Message}");
        }
    }

    private static string ResolveScriptPath()
    {
        var path = TryResolveScriptPath();
        if (path != null)
            return path;

        throw new PKError("Missing TTS generator script at Tools/Tts/tts_generate.py.");
    }

    private static string? TryResolveScriptPath()
    {
        var candidates = new[]
        {
            Path.Combine(AppContext.BaseDirectory, "Tools", "Tts", "tts_generate.py"),
            Path.Combine(Directory.GetCurrentDirectory(), "PluralKit.Bot", "Tools", "Tts", "tts_generate.py"),
            Path.Combine(Directory.GetCurrentDirectory(), "Tools", "Tts", "tts_generate.py")
        };

        return candidates.FirstOrDefault(global::System.IO.File.Exists);
    }
}
