name: Build and Push .NET Docker Image to GHCR

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
    paths:
    - '.dockerignore'
    - '.github/workflows/dotnet-docker.yml'
    - 'ci/Dockerfile.dotnet'
    - 'ci/dotnet-version.sh'
    - 'ci/entrypoint.sh'
    - 'ci/download-piper-voices.sh'
    - 'Myriad/**'
    - 'PluralKit.API/**'
    - 'PluralKit.Bot/**'
    - 'PluralKit.Core/**'

jobs:
  build-and-push:
    name: '.net docker build and push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ci/Dockerfile.dotnet
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
