name: .net checks

on:
  push:
    paths:
    - .github/workflows/dotnet.yml
    - global.json
    - 'Myriad/**'
    - 'PluralKit.Bot/**'
    - 'PluralKit.Core/**'
    - 'PluralKit.Tests/**'
  pull_request:
    paths:
    - .github/workflows/dotnet.yml
    - global.json
    - 'Myriad/**'
    - 'PluralKit.Bot/**'
    - 'PluralKit.Core/**'
    - 'PluralKit.Tests/**'

jobs:
  test:
    name: 'run .net tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run automated tests
        run: dotnet test --configuration Release

  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Run dotnet-format
        run: dotnet format --no-restore --verify-no-changes
